// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOXYDW00amPDfymyULRtpPM7ef4ctWsXM',
    appId: '1:437034798080:web:36b28700a35e91c2ebdce5',
    messagingSenderId: '437034798080',
    projectId: 'confidease-c5f7e',
    authDomain: 'confidease-c5f7e.firebaseapp.com',
    storageBucket: 'confidease-c5f7e.firebasestorage.app',
    measurementId: 'G-KJ864B8F45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNgCb5gI0c8kk-wH4Q5A6rLpqbH2Mf1vQ',
    appId: '1:437034798080:android:e53f24f6786b6d7febdce5',
    messagingSenderId: '437034798080',
    projectId: 'confidease-c5f7e',
    storageBucket: 'confidease-c5f7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3iOkd8FviVWDecRexF-HYQ1gNxW8ilvI',
    appId: '1:437034798080:ios:8be93e114b546dadebdce5',
    messagingSenderId: '437034798080',
    projectId: 'confidease-c5f7e',
    storageBucket: 'confidease-c5f7e.firebasestorage.app',
    iosBundleId: 'com.example.confidease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3iOkd8FviVWDecRexF-HYQ1gNxW8ilvI',
    appId: '1:437034798080:ios:8be93e114b546dadebdce5',
    messagingSenderId: '437034798080',
    projectId: 'confidease-c5f7e',
    storageBucket: 'confidease-c5f7e.firebasestorage.app',
    iosBundleId: 'com.example.confidease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOXYDW00amPDfymyULRtpPM7ef4ctWsXM',
    appId: '1:437034798080:web:52424baf2582a79bebdce5',
    messagingSenderId: '437034798080',
    projectId: 'confidease-c5f7e',
    authDomain: 'confidease-c5f7e.firebaseapp.com',
    storageBucket: 'confidease-c5f7e.firebasestorage.app',
    measurementId: 'G-S13114H9QH',
  );

}